name: nanoBioforms
favicon: null
layout_spectrum: 0.34659577906131744
typography_spectrum: 0.3065144019201398
title: submicron particle flow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8313744543120265
  lightness: 0.5242395864333957
  saturation: 0.5040871924720705
  rhythmicContrast: 0.09214492538012564
purpose: []
